/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
    kotlin("jvm") version "1.4.31"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.slf4j:slf4j-api:1.7.25")
    implementation("org.eclipse.jetty:jetty-server:9.4.33.v20201020")
    implementation("org.eclipse.jetty:jetty-webapp:9.4.33.v20201020")
    implementation("org.eclipse.jetty.websocket:websocket-server:9.4.33.v20201020")
    implementation("org.eclipse.jetty.websocket:websocket-servlet:9.4.33.v20201020")
    testImplementation("org.slf4j:slf4j-simple:1.7.25")
    testImplementation("junit:junit:4.12")
    testImplementation("org.mockito:mockito-core:1.10.19")
    testImplementation("org.powermock:powermock-module-junit4:1.7.4")
    testImplementation("org.powermock:powermock-api-mockito:1.7.4")
    testImplementation("org.apache.httpcomponents:httpclient:4.5.6")
    testImplementation("org.freemarker:freemarker:2.3.28")
    testImplementation("com.google.code.gson:gson:2.8.5")
    testImplementation("org.eclipse.jetty.websocket:websocket-client:9.4.33.v20201020")
}

group = "com.sparkjava"
version = "2.9.4-SNAPSHOT"
description = "Spark"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
